# Generated by Django 5.0.4 on 2024-04-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='total_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
